name: Deploy Slideshow to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - presentation/slides.md
      - presentation/package.json
      - presentation/package-lock.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: cd presentation && npm install # Change directory to presentation before install

      - name: Build HTML
        run: cd presentation && npx slidev build --base=/presentation # Change directory to presentation before build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: presentation/dist # Specify the correct path for the artifact

  deploy:
    needs: build
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
